<template>
  <div class="bj-stage" :class="{ 'round-active': isActive }">
    <!-- Table decorations cropped from the reference sheet -->
    <CasinoArt source="blackjack" :x="318" :y="282" :w="114" :h="120" class="bj-deck-art" />
    <CasinoArt source="blackjack" :x="550" :y="261" :w="409" :h="78" class="bj-tray-art" />
    <CasinoArt source="blackjack" :x="1018" :y="261" :w="185" :h="177" class="bj-shoe-art" />

    <!-- Rule ribbon -->
    <div class="bj-ribbon" aria-hidden="true">
      <svg viewBox="0 0 800 120">
        <path d="M30 12Q400 155 770 12L761 39 791 53Q400 203 9 53L39 39Z" fill="none" stroke="#d8dce9" />
        <path id="casino-bj-ribbon-curve" d="M100 62Q400 165 700 62" fill="none" />
        <text font-size="22" fill="#a3a7b6" text-anchor="middle">
          <textPath href="#casino-bj-ribbon-curve" startOffset="50%">{{ ribbonText }}</textPath>
        </text>
      </svg>
    </div>

    <!-- Hands rendered by the vanilla renderer -->
    <div ref="handsEl" class="bj-hands"></div>
  </div>
</template>

<script setup lang="ts">
/**
 * BlackjackTable — table scene (decorations + rule ribbon + dealt hands).
 * Card markup is generated by the vanilla renderer into `.bj-hands`; the
 * positioning styles for renderer output live in assets/casino/game-scenes.css
 * (renderer-injected DOM has no Vue scope attributes, hence the global CSS).
 */
import { computed, ref, watchEffect } from 'vue'
import { useI18n } from 'vue-i18n'
import CasinoArt from './CasinoArt.vue'
import { blackjackHandView, renderHands } from './renderers'
import type { CasinoBlackjackConfig, CasinoBlackjackGame } from '@/api/casino'

const props = defineProps<{
  game: CasinoBlackjackGame | null
  rules?: CasinoBlackjackConfig | null
}>()

const { t } = useI18n()

const handsEl = ref<HTMLElement | null>(null)

const isActive = computed(() => props.game?.status === 'active')

const labels = computed(() => ({
  dealer: t('casino.blackjack.dealer'),
  you: t('casino.blackjack.you'),
  soft: t('casino.blackjack.soft')
}))

const ribbonText = computed(() => {
  const pays = props.rules?.blackjack_pays ?? 2.5
  const paysText = pays === 2.5 ? '3:2' : `${pays - 1}:1`
  const dealerRule = props.rules?.dealer_stands_soft17
    ? t('casino.blackjack.ruleDealerStands')
    : t('casino.blackjack.ruleDealerHits')
  return [t('casino.blackjack.rulePays', { pays: paysText }), dealerRule, t('casino.blackjack.ruleNoInsurance')].join(
    '　|　'
  )
})

watchEffect(() => {
  renderHands(handsEl.value, blackjackHandView(props.game, labels.value))
})
</script>

<style scoped>
.bj-stage {
  position: relative;
  width: 100%;
  min-height: 500px;
  overflow: hidden;
  border-radius: 20px;
  background:
    radial-gradient(120% 90% at 50% 0%, #ffffff 0%, #eef2fb 55%, #dfe6f5 100%);
  box-shadow: inset 0 0 0 1px rgba(93, 108, 160, 0.14);
}

.bj-deck-art {
  position: absolute;
  left: 4.2%;
  top: 3.5%;
  width: 12.5%;
  border-radius: 10px;
  box-shadow: 0 8px 18px rgba(60, 70, 120, 0.18);
}

.bj-tray-art {
  position: absolute;
  left: 50%;
  top: 3%;
  transform: translateX(-50%);
  width: 42%;
  border-radius: 10px;
}

.bj-shoe-art {
  position: absolute;
  right: 4%;
  top: 3.5%;
  width: 17%;
  border-radius: 12px;
  box-shadow: 0 8px 18px rgba(60, 70, 120, 0.18);
}

.bj-ribbon {
  position: absolute;
  left: 50%;
  bottom: 6%;
  transform: translateX(-50%);
  width: min(92%, 760px);
  pointer-events: none;
}
.bj-ribbon svg {
  display: block;
  width: 100%;
}

@media (max-width: 760px) {
  .bj-stage {
    min-height: 420px;
  }
  .bj-deck-art,
  .bj-shoe-art {
    display: none;
  }
  .bj-tray-art {
    width: 70%;
  }
}
</style>
